application: webwikify
version: 1
runtime: python
api_version: 1

handlers:
- url: /server/.*
  script: main.py
  
- url: /static2
  static_dir: static2

- url: /technology.*
  static_files: static2/technology.html
  upload: static2/technology.html
  
- url: /bookmarklet.*
  static_files: static2/bookmarklet.html
  upload: static2/bookmarklet.html

- url: /more.*
  static_files: static2/more.html
  upload: static2/more.html
  
- url: /favicon.ico
  static_files: static2/favicon.ico
  upload: static2/favicon.ico
  
- url: /.*
  static_files: static2/intro.html
  upload: static2/intro.html