application: webwikify
version: 2
runtime: python
api_version: 1

handlers:
- url: /wkserver.*
  script: main2.py

- url: /server/.*
  script: main.py
  
- url: /static2
  static_dir: static2
  
- url: /static3
  static_dir: static3
  
- url: /Project_Wikify_files
  static_dir: site/Project_Wikify_files

- url: /favicon.ico
  static_files: static2/favicon.ico
  upload: static2/favicon.ico

- url: /static/core.*
  static_files: static2/oldcore.js
  upload: static2/oldcore.js
  
- url: /
  static_files: site/Project_Wikify.html
  upload: site/Project_Wikify.html

- url: /.+
  script: redirect.py